"""depot und comp id bei offer

Revision ID: 073e42a6662a
Revises: d0772783da4c
Create Date: 2023-06-10 10:17:25.015087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073e42a6662a'
down_revision = 'd0772783da4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('depot_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('depot_id')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
