"""foreign key in offer

Revision ID: c88a748c3ee4
Revises: cdec8c1f4726
Create Date: 2023-06-07 13:32:23.195310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88a748c3ee4'
down_revision = 'cdec8c1f4726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_offer_market_id', 'market', ['market_id'], ['market_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offer_market_id', type_='foreignkey')

    # ### end Alembic commands ###
