"""Currency Tabelle _code spalte

Revision ID: cdec8c1f4726
Revises: 45381c567107
Create Date: 2023-06-05 22:16:28.957801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdec8c1f4726'
down_revision = '45381c567107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_currency_code', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_column('market_currency_code')

    # ### end Alembic commands ###
